export const paintings = [
    {
        id: 1,
        title: "I need You tonight",
        src: "fotos/1. I need You tonight.jpg",
        publishing_date: "Oktober 2019",
        material: "Sprühlack, Acryl und Tinte auf Leinwand",
        width: 120,
        height: 150,
    },
    {
        id: 2,
        title: "Frau mit Mantel",
        src: "fotos/2. Frau mit Mantel.jpg",
        publishing_date: "Oktober 2019",
        material: "Sprühlack, Acryl und Tinte auf Leinwand",
        width: 120,
        height: 150,
    },
    {
        id: 3,
        title: "Disco Love",
        src: "fotos/3. Disco Love.jpg",
        publishing_date: "Oktober 2019",
        material: "Sprühlack, Acryl und Tinte auf Leinwand",
        width: 120,
        height: 150,
    },
    {
        id: 4,
        title: "Vino Vernissage",
        src: "fotos/4. Vino Vernissage.jpg",
        publishing_date: "November 2019",
        material: "Sprühlack, Acryl, Tinte und Ölkreide auf Leinwand",
        width: 120,
        height: 150,
    },
    {
        id: 5,
        title: "Drinking out until I drown too",
        src: "fotos/5. Drinking out until I drown too.jpg",
        publishing_date: "November 2019",
        material: "Sprühlack, Acryl und Tinte auf Leinwand",
        width: 120,
        height: 150,
    },
    {
        id: 6,
        title: "Confused",
        src: "fotos/6. Confused.jpg",
        publishing_date: "Dezember 2019",
        material: "Sprühlack, Acryl und Tinte auf Leinwand",
        width: 120,
        height: 150,
    },
    {
        id: 7,
        title: "QUEEN NO.1",
        src: "fotos/7. QUEEN NO.1.jpg",
        publishing_date: "Dezember 2019",
        material: "Sprühlack, Acryl und Tinte auf Leinwand",
        width: 120,
        height: 150,
    },
    {
        id: 8,
        title: "QUEEN NO.2",
        src: "fotos/8. QUEEN NO.2.jpg",
        publishing_date: "Dezember 2019",
        material: "Sprühlack, Acryl und Tinte auf Leinwand",
        width: 120,
        height: 150,
    },
    {
        id: 9,
        title: "Dions Guernica",
        src: "fotos/9. Dions Guernica.jpg",
        publishing_date: "Dezember 2019",
        material: "Sprühlack, Acryl und Tinte auf Leinwand",
        width: 120,
        height: 150,
    },
    {
        id: 10,
        title: "I invite my mind to a horse ride",
        src: "fotos/10. I invite my mind to a horse ride.jpg",
        publishing_date: "Dezember 2019",
        material: "Sprühlack, Acryl und Tinte auf Leinwand",
        width: 120,
        height: 150,
    }
]